version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes: 
      - ./var/lib/mysql:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
